apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torrent-stream-server
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torrent-stream-server
            port:
              number: {{ .Values.service.port }}
{{- if Values.ingress.host -}}
    host: {{ Values.ingress.host }}
{{- end -}}
